

-- user var 5 sual cavab verir link yaranir dostu ile paylasir sonra ise 
--dostu hemin suallari cavablandirir ve user ile dostunun cavablari muqayise olunur

--onda user  cedvelinden yaradiram texmini  username unique olsun lazim olsa artiraram first_name last_name
create table users(
user_id number generated by default  as identity primary key,
username varchar2(100)unique,
telegram_id varchar2(50) unique,
created_at timestamp default current_timestamp
);


INSERT INTO users (username, telegram_id) 
VALUES ('arzu', '123456789');


select u.*,to_char(created_at,'mm-dd-yyyy') datee   from users u




--suallar cedveli manual

CREATE TABLE questions (
    question_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text VARCHAR2(500)
);
select * from questions
--user cavablari
create table user_answers(
answer_id  number generated by default as identity primary key,
user_id number references users(user_id),
question_id number references questions(question_id),
answer_text varchar2(500)
);

select * from user_answers

--friend cavablari
create table friend_answers(
friend_answer_id number generated by default as identity primary key,
friend_id number references users(user_id),
question_id number references questions(question_id),
answer_text varchar2(500)
);


--result cedveli
--user_id - sual verib dostu ile muqayise edir
create table results(
result_id number generated by default as identity primary key,
user_id number references users(user_id),
friend_user_id number references users(user_id),
score number,
created_at timestamp default current_timestamp

);
insert into  questions (question_text) values ('What is my  favorite color');
insert into  questions (question_text) values ('What is my favorite meal');
insert into  questions (question_text) values (' Where I would visit ');
insert into  questions (question_text) values ('What is my favorite artist');
insert into  questions (question_text) values ('What is my favorite hobby');

select *from questions;

-- user_id = 1 (arzu)
INSERT INTO user_answers (user_id, question_id, answer_text) VALUES (1, 1, 'Blue');
INSERT INTO user_answers (user_id, question_id, answer_text) VALUES (1, 2, 'Pizza');
INSERT INTO user_answers (user_id, question_id, answer_text) VALUES (1, 3, 'Japan');
INSERT INTO user_answers (user_id, question_id, answer_text) VALUES (1, 4, 'The Weekend ');
INSERT INTO user_answers (user_id, question_id, answer_text) VALUES (1, 5, 'Coding');

select * from user_answers

select * from users
INSERT INTO users (username, telegram_id) VALUES ('Nuray', '987654321');

INSERT INTO friend_answers (friend_id, question_id, answer_text) VALUES (21, 1, 'Blue');
INSERT INTO friend_answers (friend_id, question_id, answer_text) VALUES (21, 2, 'Burger');
INSERT INTO friend_answers (friend_id, question_id, answer_text) VALUES (21, 3, 'Japan');
INSERT INTO friend_answers (friend_id, question_id, answer_text) VALUES (21, 4, 'Adele');
INSERT INTO friend_answers (friend_id, question_id, answer_text) VALUES (21, 5, 'Reading');


--user_id = 1 (arzu) dostu id = 21 (Nuray)
--user suallari ve dost suallari muqayise olunur
--test ucundur 
select * from friend_answers
INSERT INTO results (user_id, friend_user_id, score)
VALUES (1, 21, 80);


SELECT r.result_id, u.username AS user_name, f.username AS friend_name, r.score
FROM results r
JOIN users u ON r.user_id = u.user_id
JOIN users f ON r.friend_user_id = f.user_id;

